[package]
name = "jwt"
type = "bin"
author = "Hyli"
version = "0.1.0"

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
jwt = {tag = "main", git = "https://github.com/zkemail/noir-jwt" }


# You may need the standard library depending on your setup
# std = { tag = "v0.22.0", git = "https://github.com/noir-lang/noir" }
